using System.IO;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// StartScreen scene manager 
/// </summary>
public class StartScreenManager : MonoBehaviour
{
    /// <summary>
    /// Referece to the userlist to check whether an user account is present
    /// </summary>
    public UserList userList;

    /// <summary>
    /// Check on load whether a user is already present, 
    /// if not load the UserCreationScreen scene so the user can create a new account
    /// </summary>
    void Awake()
    {
        if (!File.Exists(UserList.PATH) || userList.GetUsers().Count <= 0)
        {
            SceneManager.LoadScene("Accounts/Scenes/UserCreationScreen");
        }
    }
}
